# Generated by Django 2.1.7 on 2020-09-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
